package othello.Exception;




/**
 * Test program for ArgumentException.
 * Lab Exercise SoftwareSystems
 * @author Jip Spel
 * @version $Revision: 1.0 $
 */
public class ArgumentExceptionTest {
/**
    /** Test variable for a <tt>WrongArgumentException</tt> object. *
    private WrongArgumentException wrongArgumentException;

    @BeforeEach
    public void setUp() {
        wrongArgumentException = new WrongArgumentException();
    }

    /**
     * Test <tt>TooFewArgumentsException</tt>
     *
    @Test
    public void testTooFewArgumentsException() {
        TooFewArgumentsException exception = new TooFewArgumentsException();
        assertTrue(exception instanceof WrongArgumentException);
        assertFalse(exception.getMessage().equals(wrongArgumentException.getMessage()));
    }

    /**
     * Test <tt>ArgumentLengthsDifferException</tt>
     *
    @Test
    public void testArgumentLengthsDifferException() {
        ArgumentLengthsDifferException exception = new ArgumentLengthsDifferException(2, 3);
        assertTrue(exception instanceof WrongArgumentException);
        assertFalse(exception.getMessage().equals(wrongArgumentException.getMessage()));
    }*/
}
